In [1]:
import numpy as np

In [3]:
# Task 1
locations = 500
days = 365

temperature = np.random.uniform(-10, 40, (locations, days))

humidity = np.random.uniform(0, 100, (locations, days))

print("Temperature: \n",temperature)
print("Humidity: \n",humidity)

Temperature: 
 [[-5.08151446  0.44770203 -3.34499533 ... -4.8879734   6.07837945
  30.16803631]
 [18.83475227  6.04915677 -1.20127641 ...  6.38329086  9.78592291
  32.28748168]
 [20.68222746 36.53735249  4.02401499 ...  6.42934005 33.50077897
  16.71700504]
 ...
 [-1.06782885 31.92821217 -4.23515919 ... 14.92697846  7.98298614
  35.9028051 ]
 [10.14242279 32.65126185 38.82099927 ... 23.76994737 -6.63639659
   8.6442909 ]
 [-3.41757624 12.39385484  7.75753286 ... 20.80125919 -4.33049611
  26.8154751 ]]
Humidity: 
 [[ 0.74526005 46.05809726 99.90521605 ... 46.95607711 15.64074931
  92.66822113]
 [34.46106389 91.13494722 88.37241781 ... 75.33272822  1.2135781
  67.48841795]
 [25.80591981 69.20566123 45.72729972 ... 95.23568338 63.07641297
  78.08228103]
 ...
 [72.6285255  30.33849355 20.9449995  ...  3.26134442 50.49775875
   7.48351163]
 [ 4.03533286 76.37335186 51.30169404 ... 32.86499547 66.52922894
  27.50154078]
 [88.72733446 88.70321639 28.88274092 ... 39.6163036  92.48140959
   7.1

In [16]:
# Task 2
total = temperature.size
missing_count = int(total * 0.05)

temperature_with_missing_data = temperature.copy()
humidity_with_missing_data = humidity.copy()

temperature_missing_indice = np.random.choice(total, missing_count, replace=False)
humidity_missing_indices = np.random.choice(total, missing_count, replace=False)

np.put(temperature_with_missing_data, temperature_missing_indice, None)
np.put(humidity_with_missing_data, humidity_missing_indices, None)

temperature_missing_count = np.isnan(temperature_with_missing_data).sum()
humidity_missing_count = np.isnan(humidity_with_missing_data).sum()

print("Temperature missing data count: ", temperature_missing_count)
print("Himdity missing data count: ", humidity_missing_count)
print("Total missing data: ", temperature_missing_count + humidity_missing_count)


Temperature missing data count:  9125
Himdity missing data count:  9125
Total missing data:  18250


In [32]:
# Task 3
temperature_fahrenheit = temperature_with_missing_data * 9/5 + 32

# A common formula for "feels like" index is: DI = T - (0.55 - 0.0055 * RH) * (T - 58),

# Calculate discomfort index while handling NaN values (ignoring NaNs)
discomfort_index = temperature_fahrenheit - (0.55 - 0.0055 * humidity_with_missing_data) * (temperature_fahrenheit - 58)

discomfort_index = np.where(discomfort_index > 80, 80, discomfort_index)

print("First 10 location's (5 days) Temperature in Fahrenheit: \n", temperature_fahrenheit[:10, :5])
print("First 10 location's (5 days) Discomfort index: \n", discomfort_index[:10, :5])



First 10 location's (5 days) Temperature in Fahrenheit: 
 [[ 22.85327397  32.80586366  25.97900841  43.34286476  69.74292605]
 [ 65.90255408          nan  29.83770246  66.72223364  33.51547591]
 [ 69.22800943  97.76723449  39.24322698  61.63109093  24.09066524]
 [ 90.79320466  40.58621687  68.82208555  16.76557538  60.32758892]
 [ 31.31790955  45.69731409 100.30777806  64.03962647  45.5284262 ]
 [ 56.81928004  73.70128797  55.86939678  97.83076675  25.26355701]
 [ 91.64289967  20.14005694  42.63191239          nan  52.94598878]
 [ 56.55837026  67.85980742  92.07426346  69.95242722  49.35979161]
 [ 47.58784836          nan  97.08959109  39.26418588 103.29207672]
 [ 47.3818652   32.44486457  69.56714388  37.49402253  35.85724707]]
First 10 location's (5 days) Discomfort index: 
 [[42.03990931 40.28047174 25.99570133 45.16126734 67.01323599]
 [63.05396665         nan 31.63872932 65.70509461 39.52211277]
 [64.64622436 80.         44.84212094 59.79611107 29.66421961]
 [80.         40.642630

In [19]:
# Task 4
jan_temp = temperature[:, :31]

avg_jan_temp = np.nanmean(jan_temp)  # Calculate mean, ignoring NaNs

print(f"Average January Temperature of all 500 locations: {avg_jan_temp:.2f} °C")



Average January Temperature of all 500 locations: 15.10 °C


In [22]:
#Task 5
temperature_copy = temperature.copy()
temperature_copy[temperature > 35] = np.nan  # Replace temperatures > 35°C with NaN

null_counts_per_loc = np.isnan(temperature_copy).sum(axis=1) # sum all null values

for loc, null_count in enumerate(null_counts_per_loc):
    print(f"Location {loc + 1}: {null_count} potential error values (None)")



Location 1: 47 potential error values (None)
Location 2: 32 potential error values (None)
Location 3: 44 potential error values (None)
Location 4: 47 potential error values (None)
Location 5: 31 potential error values (None)
Location 6: 29 potential error values (None)
Location 7: 42 potential error values (None)
Location 8: 37 potential error values (None)
Location 9: 29 potential error values (None)
Location 10: 38 potential error values (None)
Location 11: 40 potential error values (None)
Location 12: 28 potential error values (None)
Location 13: 36 potential error values (None)
Location 14: 44 potential error values (None)
Location 15: 41 potential error values (None)
Location 16: 50 potential error values (None)
Location 17: 32 potential error values (None)
Location 18: 41 potential error values (None)
Location 19: 37 potential error values (None)
Location 20: 31 potential error values (None)
Location 21: 41 potential error values (None)
Location 22: 34 potential error values (Non

In [37]:
# Task 6
import numpy as np


days_in_months = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

# Create slices for each quarter
quarter1 = temperature[:, :31]   
quarter2 = temperature[:, 31:121]
quarter3 = temperature[:, 121:273]
quarter4 = temperature[:, 273:]   


avg_quarter_1 = np.nanmean(quarter1, axis=1)
avg_quarter_2 = np.nanmean(quarter2, axis=1)
avg_quarter_3 = np.nanmean(quarter3, axis=1)
avg_quarter_4 = np.nanmean(quarter4, axis=1)

# Combine the averages into a single array
quarterly_averages = np.column_stack((avg_quarter_1,
                                       avg_quarter_2,
                                       avg_quarter_3,
                                       avg_quarter_4))

print("Fist 10 Locations averages quater wise:\n", quarterly_averages[:10])


Fist 10 Locations averages quater wise:
 [[12.03734868 16.88841498 17.3176214  13.76227243]
 [17.09930803 14.24768003 15.26228417 15.40605672]
 [12.22423187 16.70407827 17.18716087 15.19642895]
 [15.04632495 15.8144961  16.76676309 15.068597  ]
 [14.32821723 13.0419795  14.1578667  13.57520863]
 [14.26611193 15.9103061  12.44225081 15.76649337]
 [18.44428152 17.35129706 14.69588881 15.89746584]
 [16.08337365 11.98959997 13.68951073 14.80333619]
 [17.61419893 14.85298584 11.86375645 15.28090369]
 [ 9.39525494 15.22592908 13.04026667 15.93346773]]


In [26]:
# Task 7
dry_days_count = np.zeros(humidity.shape[0], dtype=int)  # For "Dry" days
humid_days_count = np.zeros(humidity.shape[0], dtype=int)  # For "Humid" days

# Classify humidity levels
dry_days_count = np.sum(humidity < 30, axis=1)  # Count "Dry" days
humid_days_count = np.sum(humidity > 70, axis=1)  # Count "Humid" days

# Display the results
for location in range(humidity.shape[0]):
    print(f"Location {location + 1}: {dry_days_count[location]} Dry days, {humid_days_count[location]} Humid days")



Location 1: 97 Dry days, 123 Humid days
Location 2: 115 Dry days, 98 Humid days
Location 3: 107 Dry days, 109 Humid days
Location 4: 103 Dry days, 112 Humid days
Location 5: 115 Dry days, 104 Humid days
Location 6: 106 Dry days, 111 Humid days
Location 7: 121 Dry days, 102 Humid days
Location 8: 109 Dry days, 109 Humid days
Location 9: 113 Dry days, 117 Humid days
Location 10: 112 Dry days, 105 Humid days
Location 11: 103 Dry days, 119 Humid days
Location 12: 100 Dry days, 121 Humid days
Location 13: 114 Dry days, 101 Humid days
Location 14: 103 Dry days, 114 Humid days
Location 15: 94 Dry days, 118 Humid days
Location 16: 115 Dry days, 105 Humid days
Location 17: 114 Dry days, 113 Humid days
Location 18: 112 Dry days, 103 Humid days
Location 19: 104 Dry days, 116 Humid days
Location 20: 99 Dry days, 114 Humid days
Location 21: 106 Dry days, 121 Humid days
Location 22: 97 Dry days, 122 Humid days
Location 23: 119 Dry days, 105 Humid days
Location 24: 104 Dry days, 106 Humid days
Locati

In [30]:
# Task 8
mean_pressure = 1013  # Mean atmospheric pressure in hPa as a referenceof adjustment
pressure_variation = np.random.normal(0, 5, (365,))
pressure_trend = mean_pressure + pressure_variation


adjusted_temperature_data = temperature.copy()

for day in range(365):
    pressure_adjustment = (pressure_trend[day] - mean_pressure) * 0.1 
    adjusted_temperature_data[:, day] += pressure_adjustment

print("First 10 Locations with 5 days adjusted temperature: \n", adjusted_temperature_data[:10, :5])


First 10 Locations with 5 days adjusted temperature: 
 [[-5.24177796  0.25141127 -3.98763019  6.07073205 20.67580284]
 [18.67448877  5.85286601 -1.84391128 19.05927032  0.54944165]
 [20.52196397 36.34106173  3.38138013 16.2308577  -4.68656428]
 [32.50262798  4.57382972 19.81407933 -8.69442872 15.44505999]
 [-0.53920264  7.41332818 37.30613072 17.568933    7.22330292]
 [13.62822542 22.97109144 12.61814112 36.34178871 -4.03495774]
 [32.97468077 -6.78514802  5.26398313 14.91013612 11.34417102]
 [13.48327554 19.72582447 32.73195595 20.85382231  9.35183926]
 [ 8.49965226  6.60261805 35.51824907  3.80479934 39.31421987]
 [ 8.38521717  0.05085622 20.22800063  2.82137526  1.85042562]]
